demo = (
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"dock-body",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-case",
		(
			(1.000000, -0.000019, 0.000211, ),
			(0.000019, 1.000000, 0.000118, ),
			(-0.000211, -0.000118, 1.000000, ),
		),
		(
			(3.662591, ),
			(-0.007421, ),
			(0.026560, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_6_2",
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"c2",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c2")),
	),
	"move grasped object",
	(
		2.000000,
		"discard-bin",
		(
			(0.999999, 0.000114, 0.001329, ),
			(-0.000115, 1.000000, 0.000459, ),
			(-0.001329, -0.000459, 0.999999, ),
		),
		(
			(-2.541436, ),
			(0.481380, ),
			(8.057884, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c2")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"c5",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c5")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-body_6_1",
		(
			(0.999744, 0.018954, 0.012365, ),
			(-0.018873, 0.999800, -0.006668, ),
			(-0.012489, 0.006433, 0.999901, ),
		),
		(
			(-0.349632, ),
			(-0.150696, ),
			(0.198015, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c5")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_6_2",
		1.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"dock-body",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-case",
		(
			(1.000000, 0.000000, 0.000009, ),
			(-0.000000, 1.000000, 0.000000, ),
			(-0.000009, -0.000000, 1.000000, ),
		),
		(
			(0.106290, ),
			(0.008277, ),
			(0.024922, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("c2", "Cartridge"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"release",
	(
		2.000000,
	)
),
)
