demo = (
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"dock-body",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-case",
		(
			(1.000000, -0.000013, 0.000102, ),
			(0.000013, 1.000000, -0.000007, ),
			(-0.000102, 0.000007, 1.000000, ),
		),
		(
			(3.647824, ),
			(0.012700, ),
			(0.025983, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_8_2",
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"c4",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c4")),
	),
	"move grasped object",
	(
		2.000000,
		"discard-bin",
		(
			(0.999985, -0.005451, 0.000142, ),
			(0.005451, 0.999984, 0.001494, ),
			(-0.000151, -0.001493, 0.999999, ),
		),
		(
			(-1.965898, ),
			(2.058959, ),
			(6.625202, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c4")),
	),
	"release",
	(
		2.000000,
	)
),
)
