ground_truth = (
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"open dock drawer",
	(
		"dock-body",
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_7_2",
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"discard object",
	(
		"c3",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_8_2",
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move object",
	(
		"c4",
		"dock-body_7_1",
		(
			(0.999801, -0.019925, -0.000469, ),
			(0.019925, 0.999801, -0.000232, ),
			(0.000474, 0.000223, 1.000000, ),
		),
		(
			(-0.408198, ),
			(0.006555, ),
			(0.345470, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_7_2",
		1.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"close dock drawer",
	(
		"dock-body",
	)
),
)
