demo = (
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"dock-body",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-case",
		(
			(1.000000, -0.000183, 0.000022, ),
			(0.000183, 1.000000, -0.000317, ),
			(-0.000022, 0.000317, 1.000000, ),
		),
		(
			(3.705221, ),
			(0.000380, ),
			(0.079652, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_7_2",
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"c3",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c3")),
	),
	"move grasped object",
	(
		2.000000,
		"discard-bin",
		(
			(0.999991, -0.004179, 0.000155, ),
			(0.004179, 0.999987, -0.003087, ),
			(-0.000142, 0.003088, 0.999995, ),
		),
		(
			(-1.451147, ),
			(1.286771, ),
			(6.662836, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c3")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_8_2",
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"c4",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c4")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-body_7_1",
		(
			(0.999801, -0.019925, -0.000469, ),
			(0.019925, 0.999801, -0.000232, ),
			(0.000474, 0.000223, 1.000000, ),
		),
		(
			(-0.408198, ),
			(0.006555, ),
			(0.345470, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","c4")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"press dock toggle",
	(
		2.000000,
		"dock-body_7_2",
		1.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"dock-body",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"move grasped object",
	(
		2.000000,
		"dock-case",
		(
			(1.000000, 0.000153, -0.000012, ),
			(-0.000153, 1.000000, 0.000041, ),
			(0.000012, -0.000041, 1.000000, ),
		),
		(
			(0.049983, ),
			(-0.028942, ),
			(0.001479, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("dock-case", "DockCase"),
		("dock-case_1", "Block"),
		("dock-body", "DockDrawer"),
		("dock-body_2", "DockFrontPanel"),
		("dock-body_2_1", "Prism"),
		("dock-body_2_2", "Block"),
		("dock-body_2_3", "Block"),
		("dock-body_4", "DockHandle"),
		("dock-body_4_1", "Prism"),
		("dock-body_4_2", "Prism"),
		("dock-body_5", "DockModule"),
		("dock-body_5_1", "DockSlot"),
		("c1", "Cartridge"),
		("dock-body_5_2", "DockSwitch"),
		("dock-body_5_3", "DockLED"),
		("dock-body_6", "DockModule"),
		("dock-body_6_1", "DockSlot"),
		("dock-body_6_2", "DockSwitch"),
		("dock-body_6_3", "DockLED"),
		("dock-body_7", "DockModule"),
		("dock-body_7_1", "DockSlot"),
		("c3", "Cartridge"),
		("dock-body_7_2", "DockSwitch"),
		("dock-body_7_3", "DockLED"),
		("dock-body_8", "DockModule"),
		("dock-body_8_1", "DockSlot"),
		("c4", "Cartridge"),
		("dock-body_8_2", "DockSwitch"),
		("dock-body_8_3", "DockLED"),
		("dock-case_2", "Block"),
		("dock-case_3", "Block"),
		("dock-case_4", "Block"),
		("dock-case_5", "Prism"),
		("dock-case_6", "Block"),
		("c5", "Cartridge"),
		("discard-bin", "Block"),
		("gripping", ("nothing","dock-body")),
	),
	"release",
	(
		2.000000,
	)
),
)
