demo = (
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"U_blk1",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk1")),
	),
	"move grasped object",
	(
		2.000000,
		"table",
		(
			(-0.999843, 0.017692, -0.000017, ),
			(-0.017692, -0.999843, -0.000041, ),
			(-0.000018, -0.000041, 1.000000, ),
		),
		(
			(-13.268801, ),
			(-8.297660, ),
			(4.168101, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk1")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"U_blk4",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk4")),
	),
	"move grasped object",
	(
		2.000000,
		"U_blk1",
		(
			(-0.999999, 0.001061, -0.000087, ),
			(-0.001061, -0.999999, 0.000965, ),
			(-0.000086, 0.000965, 1.000000, ),
		),
		(
			(-3.272454, ),
			(-0.171383, ),
			(3.704703, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk4")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"U_blk3",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk3")),
	),
	"move grasped object",
	(
		2.000000,
		"U_blk4",
		(
			(0.999747, -0.022447, 0.001617, ),
			(0.022449, 0.999747, -0.001397, ),
			(-0.001585, 0.001433, 0.999998, ),
		),
		(
			(-0.071792, ),
			(0.070832, ),
			(3.614694, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk3")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"U_blk2",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk2")),
	),
	"move grasped object",
	(
		2.000000,
		"U_blk1",
		(
			(-0.999984, -0.005534, -0.001333, ),
			(0.005535, -0.999985, -0.000563, ),
			(-0.001330, -0.000571, 0.999999, ),
		),
		(
			(3.349657, ),
			(0.264758, ),
			(3.525416, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk2")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"U_blk5",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk5")),
	),
	"move grasped object",
	(
		2.000000,
		"U_blk2",
		(
			(0.999917, 0.011731, -0.005248, ),
			(-0.011717, 0.999928, 0.002750, ),
			(0.005280, -0.002689, 0.999982, ),
		),
		(
			(-0.004390, ),
			(0.030385, ),
			(3.707272, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","U_blk5")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk3",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk3")),
	),
	"move grasped object",
	(
		2.000000,
		"table",
		(
			(0.999990, -0.004510, -0.000234, ),
			(0.004510, 0.999990, 0.000214, ),
			(0.000233, -0.000215, 1.000000, ),
		),
		(
			(1.320885, ),
			(-8.684838, ),
			(4.175274, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk3")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk6",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk6")),
	),
	"move grasped object",
	(
		2.000000,
		"M_blk3",
		(
			(0.999904, 0.000730, 0.013857, ),
			(-0.000743, 0.999999, 0.000975, ),
			(-0.013856, -0.000985, 0.999904, ),
		),
		(
			(-0.011148, ),
			(-0.039330, ),
			(3.557707, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk6")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk4",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk4")),
	),
	"move grasped object",
	(
		2.000000,
		"table",
		(
			(0.999968, -0.007966, 0.000070, ),
			(0.007966, 0.999968, 0.000458, ),
			(-0.000073, -0.000457, 1.000000, ),
		),
		(
			(7.887043, ),
			(-8.530935, ),
			(4.169541, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk4")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk7",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk7")),
	),
	"move grasped object",
	(
		2.000000,
		"M_blk4",
		(
			(0.999494, 0.031798, -0.000597, ),
			(-0.031798, 0.999494, 0.000870, ),
			(0.000625, -0.000851, 0.999999, ),
		),
		(
			(0.057220, ),
			(0.077963, ),
			(3.589450, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk7")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk1",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk1")),
	),
	"move grasped object",
	(
		2.000000,
		"M_blk6",
		(
			(-0.999960, -0.007850, -0.004377, ),
			(0.007845, -0.999969, 0.001098, ),
			(-0.004386, 0.001063, 0.999990, ),
		),
		(
			(2.410455, ),
			(0.290089, ),
			(3.660411, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk1")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk5",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk5")),
	),
	"move grasped object",
	(
		2.000000,
		"table",
		(
			(0.999936, 0.011252, 0.001328, ),
			(-0.011249, 0.999935, -0.001875, ),
			(-0.001349, 0.001860, 0.999997, ),
		),
		(
			(14.051610, ),
			(-8.605640, ),
			(4.175774, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk5")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk8",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk8")),
	),
	"move grasped object",
	(
		2.000000,
		"M_blk5",
		(
			(0.999998, 0.001698, 0.000664, ),
			(-0.001694, 0.999981, -0.005862, ),
			(-0.000674, 0.005861, 0.999983, ),
		),
		(
			(0.032341, ),
			(0.023818, ),
			(3.642627, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk8")),
	),
	"release",
	(
		2.000000,
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","nothing")),
	),
	"move arm and grasp",
	(
		2.000000,
		"M_blk2",
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk2")),
	),
	"move grasped object",
	(
		2.000000,
		"M_blk8",
		(
			(-0.994319, 0.106435, -0.001123, ),
			(-0.106434, -0.994319, -0.000771, ),
			(-0.001199, -0.000647, 0.999999, ),
		),
		(
			(-2.419946, ),
			(0.153725, ),
			(3.472966, ),
		),
	)
),
(
	(
		("workspace", "Workspace"),
		("table", "Block"),
		("M_blk1", "Block"),
		("M_blk2", "Block"),
		("M_blk3", "Block"),
		("M_blk4", "Block"),
		("M_blk5", "Block"),
		("M_blk6", "Block"),
		("M_blk7", "Block"),
		("M_blk8", "Block"),
		("U_blk1", "Block"),
		("U_blk2", "Block"),
		("U_blk3", "Block"),
		("U_blk4", "Block"),
		("U_blk5", "Block"),
		("discard-bin", "Block"),
		("gripping", ("nothing","M_blk2")),
	),
	"release",
	(
		2.000000,
	)
),
)
